before_script:
  - CHCP 65001

stages:
- build
- test
- report 
- release

variables:
    WP: '${CI_PROJECT_DIR}/temp/wp'

build:
    stage: build
    tags:
        - 1c-edt
    only:
        - schedules
    script:
        - executor_j11 -s $env:CI_SCRIPTS/1cicd.sbsl build
    artifacts:
        name: build
        paths:
            - build/
            - ci/
    cache:
        key: ${CI_COMMIT_REF_SLUG}
        paths:
            - $env:WP

testCore:
    stage: test
    tags:
        - 1c-edt
    only:
        - schedules
    dependencies:
        - build
    script:
        - executor_j11 -s $env:CI_SCRIPTS/1cicd.sbsl testCore
    artifacts:
        name: test
        reports:
            junit: test/junit/*.xml
        paths:
            - test/
            - ci/

testUI:
    stage: test
    tags:
        - 1c-ui
    only:
        - schedules
    dependencies:
        - build
    script:
        - executor_j11 -s $env:CI_SCRIPTS/1cicd.sbsl testUI
    artifacts:
        name: test
        reports:
            junit: test/junit/*.xml
        paths:
            - test/
            - ci/

pages:
    stage: report
    tags:
        - 1c-edt
    only:
        - schedules
    dependencies:
        - testUI
    script:
        - executor_j11 -s $env:CI_SCRIPTS/1cicd.sbsl pages
    artifacts:
        paths:
            - ci/
            - public/
    environment:
        name: allure
        url: https://${CI_SERVER_HOST}/${CI_PROJECT_PATH}/-/jobs/${CI_JOB_ID}/artifacts/file/public/index.html

release:
    stage: release
    tags:
        - 1c-edt
    only:
        - schedules
    dependencies:
        - testCore
        - testUI
        - pages
    script:
        - executor_j11 -s $env:CI_SCRIPTS/1cicd.sbsl release