before_script:
  - CHCP 65001

stages:
- build
- test
- report 
- release

variables:
    WP: '${CI_PROJECT_DIR}/temp/wp'

buildMaster:
    stage: build
    tags:
        - 1c-edt
    only:
        - master
    script:
        - executor_j11 -s $env:CI_SCRIPTS/1cicd.sbsl buildMaster
    artifacts:
        name: build
        paths:
            - build/
            - ci/
    cache:
        key: ${CI_COMMIT_REF_SLUG}
        paths:
            - $env:WP

buildMergeRequest:
    stage: build
    tags:
        - 1c-edt
    only:
        - merge_requests
    script:
        - executor_j11 -s $env:CI_SCRIPTS/1cicd.sbsl buildMergeRequest
    artifacts:
        name: build
        paths:
            - build/
            - ci/

buildRelease:
    stage: build
    tags:
        - 1c-edt
    only:
        - schedules
    script:
        - executor_j11 -s $env:CI_SCRIPTS/1cicd.sbsl buildRelease
    artifacts:
        name: build
        paths:
            - build/
            - ci/
    cache:
        key: ${CI_COMMIT_REF_SLUG}
        paths:
            - $env:WP

testCore:
    stage: test
    tags:
        - 1c-edt
    only:
        - master
        - schedules
        - merge_requests
    dependencies:
        - buildMaster
        - buildMergeRequest
        - buildRelease
    script:
        - executor_j11 -s $env:CI_SCRIPTS/1cicd.sbsl testCore
    artifacts:
        name: test
        reports:
            junit: test/junit/*.xml
        paths:
            - test/
            - ci/

testUI:
    stage: test
    tags:
        - 1c-ui
    only:
        - schedules
        - merge_requests
    dependencies:
        - buildRelease
        - buildMergeRequest
    script:
        - executor_j11 -s $env:CI_SCRIPTS/1cicd.sbsl testUI
    artifacts:
        name: test
        reports:
            junit: test/junit/*.xml
        paths:
            - test/
            - ci/

code_quality:
    stage: report
    tags:
        - 1c-edt
    only:
        - master
        - merge_requests
    dependencies:
        - testCore
    script:
        - executor_j11 -s $env:CI_SCRIPTS/1cicd.sbsl qualityCode
    artifacts:
        reports:
            codequality: test/codequality/*.json
        paths:
            - test/
            - ci/

sonarQube:
    stage: report
    tags:
        - 1c-edt
    only:
        - master
    dependencies:
        - testCore
    script:
        - executor_j11 -s $env:CI_SCRIPTS/1cicd.sbsl sonarQube
    artifacts:
        paths:
            - test/
            - ci/

pages:
    stage: report
    tags:
        - 1c-edt
    only:
        - schedules
        - merge_requests
    dependencies:
        - testUI
    script:
        - executor_j11 -s $env:CI_SCRIPTS/1cicd.sbsl pages
    artifacts:
        paths:
            - ci/
            - public/
    environment:
        name: allure
        url: https://${CI_SERVER_HOST}/${CI_PROJECT_PATH}/-/jobs/${CI_JOB_ID}/artifacts/file/public/index.html

release:
    stage: release
    tags:
        - 1c-edt
    only:
        - schedules
    dependencies:
        - testCore
        - testUI
        - pages
    script:
        - executor_j11 -s $env:CI_SCRIPTS/1cicd.sbsl release
