before_script:
  - CHCP 65001

stages:
- build
- test
- report 

variables:
    WP: '${CI_PROJECT_DIR}/temp/wp'

buildMR:
    stage: build
    tags:
        - edt
    only:
        - merge_requests
    script:
        - executor_j11 -s $env:CI_SCRIPTS/1cicd.sbsl buildMR
    artifacts:
        name: build
        paths:
            - build/
            - ci/
    cache:
        key: ${CI_COMMIT_REF_SLUG}
        paths:
            - $env:WP

testCore:
    stage: test
    tags:
        - edt
    only:
        - merge_requests
    dependencies:
        - buildMR
    script:
        - executor_j11 -s $env:CI_SCRIPTS/1cicd.sbsl testCore
    artifacts:
        name: test
        reports:
            junit: test/junit/*.xml
        paths:
            - test/
            - ci/

testUI:
    stage: test
    tags:
        - edt
    only:
        - merge_requests
    dependencies:
        - buildMR
    script:
        - executor_j11 -s $env:CI_SCRIPTS/1cicd.sbsl testUI
    artifacts:
        name: test
        reports:
            junit: test/junit/*.xml
        paths:
            - test/
            - ci/
            - public/
    environment:
        name: allure
        url: https://${CI_SERVER_HOST}/${CI_PROJECT_PATH}/-/jobs/${CI_JOB_ID}/artifacts/file/public/index.html

pages:
    stage: report
    tags:
        - edt
    only:
        - merge_requests
    dependencies:
        - testUI
    script:
        - executor_j11 -s $env:CI_SCRIPTS/1cicd.sbsl pages
    artifacts:
        paths:
            - ci/
            - public/
