stages:
- build
- test 
- release

variables:
    WP: '${CI_PROJECT_DIR}/temp/wp'

build:
    stage: build
    tags:
        - edt
    only:
        - schedules
    script:
        - executor_j11 -s $env:SCRIPTS/1cicd.sbsl build
    artifacts:
        name: build
        paths:
            - build/
            - ci/
    cache:
        key: ${CI_COMMIT_REF_SLUG}
        paths:
            - $env:WP

testCore:
    stage: test
    tags:
        - edt
    only:
        - schedules
    dependencies:
        - build
    script:
        - executor_j11 -s $env:SCRIPTS/1cicd.sbsl testCore
    artifacts:
        name: test
        reports:
            junit: test/junit/
        paths:
            - test/
            - ci/

testUI:
    stage: test
    tags:
        - edt
    only:
        - schedules
    dependencies:
        - build
    script:
        - executor_j11 -s $env:SCRIPTS/1cicd.sbsl testUI
    artifacts:
        name: test
        reports:
            junit: test/junit/
        paths:
            - test/
            - ci/

release:
    stage: release
    tags:
        - edt
    only:
        - schedules
    dependencies:
        - testCore
        - testUI
    script:
        - executor_j11 -s $env:SCRIPTS/1cicd.sbsl release
